// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhWIcY3atPS2D0Ylv2LlocHjOb_luvFYo',
    appId: '1:797985824427:web:e1bf15fe3c52987735e1ee',
    messagingSenderId: '797985824427',
    projectId: 'promise-2494a',
    authDomain: 'promise-2494a.firebaseapp.com',
    databaseURL: 'https://promise-2494a-default-rtdb.firebaseio.com',
    storageBucket: 'promise-2494a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkJ61YSAc-cnAlQruJk5QlsQUd1BbeMU0',
    appId: '1:797985824427:android:ccd455c2b7ba988935e1ee',
    messagingSenderId: '797985824427',
    projectId: 'promise-2494a',
    databaseURL: 'https://promise-2494a-default-rtdb.firebaseio.com',
    storageBucket: 'promise-2494a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOW88BI6-4qB_rYO2qubKM00-54BRC9Qk',
    appId: '1:797985824427:ios:1182082c84a843b235e1ee',
    messagingSenderId: '797985824427',
    projectId: 'promise-2494a',
    databaseURL: 'https://promise-2494a-default-rtdb.firebaseio.com',
    storageBucket: 'promise-2494a.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOW88BI6-4qB_rYO2qubKM00-54BRC9Qk',
    appId: '1:797985824427:ios:1182082c84a843b235e1ee',
    messagingSenderId: '797985824427',
    projectId: 'promise-2494a',
    databaseURL: 'https://promise-2494a-default-rtdb.firebaseio.com',
    storageBucket: 'promise-2494a.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhWIcY3atPS2D0Ylv2LlocHjOb_luvFYo',
    appId: '1:797985824427:web:1d112fbe5346323d35e1ee',
    messagingSenderId: '797985824427',
    projectId: 'promise-2494a',
    authDomain: 'promise-2494a.firebaseapp.com',
    databaseURL: 'https://promise-2494a-default-rtdb.firebaseio.com',
    storageBucket: 'promise-2494a.appspot.com',
  );

}